name: "Run buildifier"
description: "Runs Bazel's lint tool buildifier"

branding:
  icon: "umbrella"
  color: "green"

inputs:
  buildifier-version:
    description: "Buildifier version"
    required: false
    default: "5.1.0"
  path:
    description: "Path in which to run buildifier,"
    required: false
    default: "."
  mode:
    description: "Mode in which to run buildifier "
    required: false
    default: "check"
  token:
    description: Used to query buildifier releases.
    default: ${{ github.token }}

outputs:
  success:
    description: "Status of the buildifier check"

runs:
  using: "composite"
  steps:
    - name: Setup buildifier
      uses: jbajic/setup-buildifier-action@v1

    - run: buildifier -r -mode check ${{ inputs.path }}
      id: buildifier-action-check
      shell: bash
      if: ${{ inputs.mode == 'check' }}

    - run: |
        buildifier -r -multi_diff ${{ inputs.path }}
        BUILDIFIER_FILES_DIFF=$(git --no-pager diff)
        git checkout .
        if [[ "$BUILDIFIER_FILES_DIFF" != '' ]]; then
          echo -e "$BUILDIFIER_FILES_DIFF"
          exit 1
        fi
      shell: bash
      if: ${{ inputs.mode != 'check' }}
